name: TypeScript

on:
  push:
  pull_request:

jobs:
  tsc:
    name: "TSC"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    - run: npm install
    - run: npx tsc --noEmit
  eslint:
    name: "eslint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "npm"
    - run: npm install
    - run: npx eslint .